# Generated by Django 4.1.5 on 2023-05-17 00:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "student"),
                            ("school_admin", "school_admin"),
                        ],
                        default="student",
                        max_length=20,
                    ),
                ),
                ("filled_form", models.BooleanField(default=False)),
                ("date_of_update", models.DateField(null=True)),
                (
                    "age",
                    models.PositiveIntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(123),
                        ],
                    ),
                ),
                ("edu_lvl", models.CharField(max_length=20, null=True)),
                ("state", models.CharField(max_length=14, null=True)),
                ("county", models.CharField(max_length=30, null=True)),
                ("school", models.CharField(max_length=50, null=True)),
                (
                    "gpa",
                    models.FloatField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("classes", models.CharField(max_length=100)),
                ("intended_major", models.CharField(max_length=20)),
                ("interests", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
