# Generated by Django 4.1.5 on 2023-05-17 00:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="age",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(123),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="userinfo", name="county", field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="userinfo", name="date_of_update", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="edu_lvl",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="gpa",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="userinfo", name="school", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="userinfo", name="state", field=models.CharField(max_length=14),
        ),
    ]
