# Generated by Django 4.1.5 on 2023-05-17 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oauth_app", "0002_alter_userinfo_age_alter_userinfo_county_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userinfo", name="filled_form",),
    ]
