# Generated by Django 4.1.5 on 2023-05-18 01:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth_app", "0003_remove_userinfo_filled_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="age",
            field=models.PositiveIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(123),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="classes",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="county",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="date_of_update",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="edu_lvl",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="gpa",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="intended_major",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="interests",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="role",
            field=models.CharField(
                choices=[("student", "student"), ("school_admin", "school_admin")],
                default="student",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="school",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="state",
            field=models.CharField(max_length=14, null=True),
        ),
    ]
