# Generated by Django 4.1.5 on 2023-05-22 00:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=500)),
                (
                    "prize_money",
                    models.FloatField(
                        verbose_name=django.core.validators.MinValueValidator(0.01)
                    ),
                ),
                ("deadline", models.DateTimeField()),
                ("date_of_posting", models.DateTimeField()),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("county", models.CharField(blank=True, max_length=100, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "organization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "min_age",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name=django.core.validators.MinValueValidator(1),
                    ),
                ),
                (
                    "max_age",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name=django.core.validators.MinValueValidator(1),
                    ),
                ),
                (
                    "min_grade",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name=django.core.validators.MinValueValidator(0),
                    ),
                ),
                (
                    "max_grade",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name=django.core.validators.MinValueValidator(0),
                    ),
                ),
                (
                    "min_gpa",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name=django.core.validators.MinValueValidator(0),
                    ),
                ),
                ("url", models.URLField()),
            ],
        ),
    ]
