# Generated by Django 4.1.5 on 2023-05-22 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("minerva", "0002_error_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="error_report",
            name="receiver",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_error_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="error_report",
            name="receiver_message",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
